-- user
INSERT INTO user (`user_id`,
                  `login_id`,
                  `hashed_password`,
                  `email`,
                  `username`,
                  `email_verified_yn`,
                  `profile_image_url`,
                  `provider_type`,
                  `role_type`,
                  `dormant`,
                  `withdrawn`,
                  `created_at`,
                  `created_by`,
                  `modified_at`,
                  `modified_by`,
                  `deleted`)
values (1,
        'ssjf409@naver.com',
        '$2a$10$4U63tKyqozSi3cU4jTE/e.6Xb8aXxrCZYuWt6aSLlvh9H/glR5Pza',
        'ssjf409@naver.com',
        '장동혁',
        0,
        'https://naver.com',
        'LOCAL',
        'USER',
        0,
        0,
        now(),
        'SYSTEM',
        now(),
        'SYSTEM',
        0);
